[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:http"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "zoho-inventory-mcp"

[services.variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"
